[package]
name = "pellucid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static="*"
const-decoder="*"
strum="*"
strum_macros="*"
primitive-types = "*"
hex = "0.4"
cbor = "0.4"
multibase = "0.9"
log = "*"
env_logger = "*"
itertools="*"